### ISSUE TITLE
Footer link goes to www.prodyct-foundry.com

### ISSUE THREAD

**Issue by neelkanta** [Product-Foundry/visualspec.org#1]
There's a typo in the footer link which goes to www.prodyct-foundry.com.

 <a href="http://www.prodyct-foundry.com" target="_blank">Product Foundry BV</a>

**Comment by relitodea** [comment]
Hi mister,

How are you? Will come soon with some dates for visit...

Btw:: i got this email notification today... I think my email is still registered somewhere there:)

Reli

**Comment by daniel-codrea** [comment]
Fixed.
